beego.Router("/{{.modelSrc}}/{{.tableName}}/add", &controllers.{{.upModelName}}Controller{}, "post:Add")
beego.Router("/{{.modelSrc}}/{{.tableName}}/delete", &controllers.{{.upModelName}}Controller{}, "get:Delete")
beego.Router("/{{.modelSrc}}/{{.tableName}}/deleteBatch", &controllers.{{.upModelName}}Controller{}, "get:DeleteBatch")
beego.Router("/{{.modelSrc}}/{{.tableName}}/update", &controllers.{{.upModelName}}Controller{}, "put:Update")
beego.Router("/{{.modelSrc}}/{{.tableName}}/detail", &controllers.{{.upModelName}}Controller{}, "get:Detail")
beego.Router("/{{.modelSrc}}/{{.tableName}}/list", &controllers.{{.upModelName}}Controller{}, "get:List")
beego.Router("/{{.modelSrc}}/{{.tableName}}/listByKey", &controllers.{{.upModelName}}Controller{}, "get:ListByKey")